exomesite/exomesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('visualization/', include('visualization.urls')),
    path('admin/', admin.site.urls),
]

exomesite/visualization/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'visualization'
urlpatterns = [
    # ex: /visualization/
    path('', views.index, name='index'),

    # ex: /visualization/search
    # The path for search must be put before the path for result,
    # otherwise '<str:gene_name2>/' mistakes 'search' as the name of a gene
    path('search/', views.search, name='search_gene'),
    
    # ex: /visualization/PCSK9
    path('<str:gene_name2>/', views.result, name='result')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serving static files during development (not deployment)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

exomesite/visualization/models.py
# NOTE: Don't try to manually change db.sqlite3 and edit tables
# unless you really know what you are doing.
# I added a field called id to by csv file and imported it but now
# am getting some errors because on the migration the id field
# shows up as autoincrement instead of serial, and thus gets registered
# as an extra field that shifted all my other fields values one column
# to the right, so the value for the annotation field became
# the value for the flag field.
# Solved this problem by reverting all migrations, redoing migrations
# for Gene and Variant model, and reimporting csv file with id column
# into the db.sqlite file.
# https://docs.djangoproject.com/en/2.0/intro/tutorial02/
# https://simpleisbetterthancomplex.com/tutorial/2016/07/26/how-to-reset-migrations.html

from django.db import models

class Gene(models.Model):
    name = models.CharField(max_length=200)
    chrom = models.CharField(max_length=200)
    strand = models.CharField(max_length=200)
    txstart = models.BigIntegerField()  # Field name made lowercase.
    txend = models.BigIntegerField()  # Field name made lowercase.
    cdsstart = models.BigIntegerField()  # Field name made lowercase.
    cdsend = models.BigIntegerField()  # Field name made lowercase.
    exoncount = models.IntegerField()  # Field name made lowercase.
    exonstarts = models.TextField()  # Field name made lowercase.
    exonends = models.TextField()  # Field name made lowercase.
    score = models.IntegerField() # value is always 0
    name2 = models.CharField(max_length=200)
    cdsstartstat = models.CharField(max_length=200)  # Field name made lowercase.
    cdsendstat = models.CharField(max_length=200)  # Field name made lowercase.
    exonframes = models.TextField()  # Field name made lowercase.

    # some genes have variants so use both names for distinguishing variants
    def __str__(self):
        return self.name2 + ' (' + self.name + ')'


# I wanted an abstract interface class called Variant that has several 
# implementations in the form of tables such as 'visualization_variant_PCSK9'
# or 'visualization_variant_SAMD11' but I can't seem to find any way to route
# Django tables based on a generic Variant class. Therefore, I combined 
# six variant tables together into a single table for testing purposes.
class Variant(models.Model):
    name = models.CharField(max_length=200)
    chrom = models.CharField(max_length=200)
    position = models.IntegerField()
    rsid = models.CharField(max_length=200)
    reference = models.CharField(max_length=200)
    alternate = models.CharField(max_length=200)
    consequence = models.CharField(max_length=200, blank = True)
    proteinconsequence = models.CharField(max_length=200, blank = True)
    transcriptconsequence = models.CharField(max_length=200, blank = True)
    filter = models.CharField(max_length=200)
    annotation = models.CharField(max_length=200)
    flags = models.CharField(max_length=200, blank = True)
    allelecount = models.IntegerField()
    allelenumber = models.BigIntegerField()
    numberofhomozygotes = models.IntegerField()
    allelefrequency = models.FloatField()
    allelecountafrican = models.IntegerField()
    allelenumberafrican = models.IntegerField()
    homozygotecountafrican = models.IntegerField()
    allelecounteastasian = models.IntegerField()
    allelenumbereastasian = models.IntegerField()
    homozygotecounteastasian = models.IntegerField()
    allelecounteuropeannonfinnish = models.IntegerField()
    allelenumbereuropeannonfinnish = models.IntegerField()
    homozygotecounteuropeannonfinnish = models.IntegerField()
    allelecountfinnish = models.IntegerField()
    allelenumberfinnish = models.IntegerField()
    homozygotecountfinnish = models.IntegerField()
    allelecountlatino = models.IntegerField()
    allelenumberlatino = models.IntegerField()
    homozygotecountlatino = models.IntegerField()
    allelecountother = models.IntegerField()
    allelenumberother = models.IntegerField()
    homozygotecountother = models.IntegerField()
    allelecountsouthasian = models.IntegerField()
    allelenumbersouthasian = models.IntegerField()
    homozygotecountsouthasian = models.IntegerField()

    def __str__(self): 
        return (
            self.name + ", chrom: " + self.chrom + 
            ", position: " + str(self.position) +
            ", reference/alternate: " + self.reference + '/' + self.alternate)

exomesite/visualization/views.py
from django.core.serializers import serialize
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from .models import Gene, Variant


# return up to the first 10 uniquely named genes from the database
def get_ten_genes():
    query_gene_list = Gene.objects.order_by('-name2')[:10]
    gene_name_set = set()
    new_gene_list = []

    # check for gene objects that have the same value in the 'name2' field 
    # exclude those in the new_gene_list
    for gene in query_gene_list:
        if gene.name2 not in gene_name_set:
            new_gene_list.append(gene)
            gene_name_set.add(gene.name2)

    return new_gene_list


# send data to homepage of the visualization app
def index(request):
    return render(request, 'visualization/index.html', {
        'sample_gene_list': get_ten_genes
    })


# send the data from querying a gene to the corresponding html page, 
# or redirect to homepage with an error message saying the gene was not found
def result(request, gene_name2):
    gene = []
    variant_list = []

    try:
        # if there are variants of the same gene, get the one with the most exons
        # however the statement .order_by('-exoncount')[0] cannot be json serialized
        # gene = Gene.objects.filter(name2=gene_name2).order_by('-exoncount')[0]

        # new query will return a queryset that can be json serialized but I will
        # have to filter out multiple transcripts of the same gene by the one with
        # the most exons (highest exoncount value) in the JavaScript
        gene = Gene.objects.filter(name2=gene_name2)
        gene_name = gene.order_by('-exoncount')[0]
        print(Gene.objects.filter(name2=gene_name2))
    except:
        error_message = "Could not find gene " + str(gene_name2)
        return render(request, 'visualization/index.html', {
            'sample_gene_list': get_ten_genes(),
            'error_message': error_message
        })

    # TODO: figure out how to handle exception case where the gene exists 
    # in visualization_gene table but the variants for that gene do not exist 
    # in the visualization_variants table
    try:
        variant_list = Variant.objects.filter(name=gene_name2)
    except Variant.DoesNotExist:
        raise Http404("Could not find variants for gene " + str(gene_name2))

    # json serialize the QuerySet of Variant objects
    return render(request, 'visualization/result.html', {
        'gene_name': gene_name,
        'gene_json': serialize('json', gene, cls=DjangoJSONEncoder),
        'variant_list_json': serialize('json', variant_list, cls=DjangoJSONEncoder)
    })


# get the name of the gene that the user inputted in the searchbox 
# and redirect to the result view with that input
def search(request):
    gene_name = request.POST.get("query_gene", "")

    # Catch exceptional case where there is no input in the searchbox
    if not gene_name:
        error_message = "Please enter a gene name"
        return render(request, 'visualization/index.html', {
            'sample_gene_list': get_ten_genes(),
            'error_message': error_message
        })

    return HttpResponseRedirect(reverse('visualization:result', args=(gene_name,)))
    

exomesite/visualization/templates/visualization/index.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <title>Exome Browser</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'visualization/css/style.css' %}" />
    </head>
    <body>
        <!-- This section is a searchbox for genes -->
        <div id="searchbox">
            <form action="{% url 'visualization:search_gene' %}" method="post">
                {% csrf_token %}
                <input id="searchbox-input" name= "query_gene" type="text" placeholder="Search for a gene...">
                <input type="submit" value="search">
            </form>

            {% if error_message %}
                <p>Error: {{ error_message }}</p>
            {% endif %}
        </div>
            {% if sample_gene_list %}
                <p>Sample List of Genes</p>
                <ul>
                {% for gene in sample_gene_list %}
                    <li><a href="{% url 'visualization:result' gene.name2 %}">{{ gene.name2 }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
               <p> There are currently no genes available in the database.</p> 
            {% endif %}
    </body>
</html>

exomesite/visualization/templates/visualization/result.html
<!DOCTYPE html>

<html lang="en-US">
    <head>
        <title>Exome Browser</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        
        {% load static %}
        <script src="{% static 'visualization/js/chart.js' %}"></script>
        <script src="{% static 'visualization/js/gene.js' %}"></script>
        <script src="{% static 'visualization/js/utils.js' %}"></script>
        <script src="{% static 'visualization/js/main.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'visualization/css/style.css' %}" />
        <!-- 
            This script below can be turned into a separate JS file later
        -->
        <script type="text/javascript">
            // global variable for storing data and drawing charts
            var chartController = null;

            $(window).on("load", function() {                
                initializeCharts("{{variant_list_json}}", "{{gene_json}}");
            });
        </script>
    </head>
    <body>
        <h5>Gene: {{ gene_name }}</h5>
        <div class="y-axis-button-container">
            <button type="button" class="MAF" value="MAF" 
                onclick="changeYAxisVariable(
                chartController, 'MAF')">MAF
            </button>
            <button type="button" class="alleleNumber" value="alleleNumber" 
                onclick="changeYAxisVariable(chartController, 'alleleNumber')">alleleNumber
            </button>
            <button type="button" class="alleleCount" value="alleleCount" 
                onclick="changeYAxisVariable(chartController, 'alleleCount')">alleleCount
            </button>
        </div>
        <div class="chart-zoomed-out"></div>
        <div class="chart-zoomed-in"></div>
    </body>
</html>